### ISSUE TITLE
App doesn't have a signup form.

### ISSUE THREAD

**Issue by jlc1541** [Intro-to-SE-Lab-Fall-20/Group-5#25]
A user must be able to signup for Potato Mail if they don't have an account previously.

**Comment by FullmetalPotato** [comment]
Users can now sign up new user accounts.

**Comment by haleyhagler227** [comment]
Please only close issues once a pull request has been merged. There is an open pull request to add a sign up page and once that pull request has changes made to it that have been requested we can look at committing it and closing this issue.
