### ISSUE TITLE
User Story: Compose, Edit and Send Emails

### ISSUE THREAD

**Issue by haleyhagler227** [Intro-to-SE-Lab-Fall-20/Group-5#6]
Create a user story with acceptance criteria for composing, editing, and sending emails.

**Comment by FullmetalPotato** [comment]
As a user of potatomail, I want to be able to compose new emails, edit the content of the email, and send the email when I am finished.

**Acceptance Criteria**

-  A user who has successfully logged in will be able to compose new emails.

- A user composing an email will be able to edit the text.

- A user composing an email will be able to send the email that was composed.
