### ISSUE TITLE
User Story: Send attachments

### ISSUE THREAD

**Issue by haleyhagler227** [Intro-to-SE-Lab-Fall-20/Group-5#9]
Create a detailed user story for sending attachments. Include acceptance criteria.

**Comment by FullmetalPotato** [comment]
As a user of potatomail, I want to be able to send attachments as part of emails I send.

Acceptance Criteria
A user who has successfully logged in will be able to add attachments to an email when composing it. Attachments are sent with the email.

**Comment by FullmetalPotato** [comment]
Nick Lambert
